"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     *
     */
    await queryInterface.bulkInsert("Products", [
      // Iphone
      {
        id: 1,
        name: "IPhone 13 Pro Max 512GB - Chính Hãng VN/A",
        desc: "Thu cũ đổi mới: Thu giá cao trợ giá đến 90%",
        image: "bla...",
        categoryId: 1,
        price: 43990000,
        discount: 10,
        guarantee: 12,
      },
      {
        id: 2,
        name: "IPhone 13 Pro Max 1TB - Chính Hãng VN/A",
        desc: "Thu cũ đổi mới: Thu giá cao trợ giá đến 90%",
        image: "bla...",
        categoryId: 1,
        price: 49990000,
        discount: 20,
        guarantee: 12,
      },
      {
        id: 3,
        name: "IPhone 14 256GB - Chính hãng VN/A",
        desc: "Giảm 250.000đ khi mua kèm gói bảo hành VIP 12 tháng 1 Đổi 1.",
        image: "bla...",
        categoryId: 1,
        price: 33990000,
        discount: 30,
        guarantee: 12,
      },
      {
        id: 4,
        name: "IPhone 14 512GB - Chính hãng VN/A",
        desc: "bla...",
        image: "bla...",
        categoryId: 1,
        price: 27990000,
        discount: 10,
        guarantee: 24,
      },
      {
        id: 5,
        name: "IPhone 14 Plus 128GB - Chính hãng VN/A",
        desc: "Giảm 250.000đ khi mua kèm gói bảo hành VIP 12 tháng 1 Đổi 1.",
        image: "bla...",
        categoryId: 1,
        price: 27990000,
        discount: 50,
        guarantee: 24,
      },
      {
        id: 6,
        name: "IPhone 14 Plus 256GB - Chính hãng VN/A",
        desc: "Giảm 250.000đ khi mua kèm gói bảo hành VIP 12 tháng 1 Đổi 1.",
        image: "bla...",
        categoryId: 1,
        price: 30990000,
        discount: 60,
        guarantee: 36,
      },
      {
        id: 7,
        name: "IPhone 14 Plus 512GB - Chính hãng VN/A",
        desc: "Giảm 250.000đ khi mua kèm gói bảo hành VIP 12 tháng 1 Đổi 1.",
        image: "bla...",
        categoryId: 1,
        price: 36990000,
        discount: 60,
        guarantee: 12,
      },
      {
        id: 8,
        name: "IPhone 14 Pro Max 128GB - Chính hãng VN/A",
        desc: "iPhone 14 Pro Max 128GB - Chính hãng VN/A",
        image: "bla...",
        categoryId: 1,
        price: 34990000,
        discount: 75,
        guarantee: 24,
      },
      // end Iphone>

      // Ipad
      {
        id: 9,
        name: "Ipad Air 5 512GB 5G - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        price: 30990000,
        discount: 10,
        guarantee: 12,
      },
      {
        id: 10,
        name: "Ipad Air 5 64GB Wifi - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        price: 16990000,
        discount: 5,
        guarantee: 24,
      },
      {
        id: 11,
        name: "Ipad Air 5 64GB 5G - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        price: 33990000,
        discount: 30,
        guarantee: 14,
      },
      {
        id: 12,
        name: "Ipad Air 5 256GB Wifi - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        price: 20990000,
        discount: 25,
        guarantee: 12,
      },
      {
        id: 13,
        name: "Ipad Air 5 256GB 5G - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        price: 27990000,
        discount: 12,
        guarantee: 12,
      },
      {
        id: 14,
        name: "Ipad Gen 10 2022 Wifi + 5G - 256GB - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        price: 30990000,
        discount: 60,
        guarantee: 20,
      },
      {
        id: 15,
        name: "Ipad Gen 10 2022 Wifi + 5G - 64GB - Chính hãng VN",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ..",
        image: "bla...",
        categoryId: 2,
        price: 16490000,
        discount: 60,
        guarantee: 24,
      },
      {
        id: 16,
        name: "Ipad Pro 11 inch M2 2022 Wifi + 5G - Chính hãng VN - MNYD3ZA/A",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 2,
        guarantee: 12,
        price: 34990000,
      },
      // end Ipad>

      // Apple watch
      {
        id: 17,
        name: "Apple Watch SE 2022 LTE 44mm - Chính hãng VN/A",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 3,
        price: 19990000,
        discount: 10,
        guarantee: 12,
      },
      {
        id: 18,
        name: "Apple Watch S8 LTE 41mm viền thép dây cao su - Chính hãng VN/A",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 3,
        price: 19990000,
        discount: 5,
        guarantee: 24,
      },
      {
        id: 19,
        name: "Apple Watch S8 LTE 45mm viền thép dây cao su - Chính hãng VN/A",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 3,
        price: 21990000,
        discount: 30,
        guarantee: 14,
      },
      {
        id: 20,
        name: "Apple Watch S8 LTE 41mm viền thép dây thép - Chính hãng VN/A",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 3,
        price: 18490000,
        guarantee: 12,
      },
      {
        id: 21,
        name: "Apple Watch S8 LTE 45mm viền thép dây thép - Chính hãng VN/A",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 3,
        price: 20790000,
        discount: 12,
        guarantee: 12,
      },
      {
        id: 22,
        name: "Apple Watch Ultra LTE 49mm Dây Ocean Band - Chính hãng VN/A",
        desc: "Ưu đãi từ 5% – 30% khi mua phụ kiện",
        image: "bla...",
        categoryId: 3,
        price: 23990000,
        discount: 60,
        guarantee: 20,
      },
      {
        id: 23,
        name: "Apple Watch Ultra LTE 49mm Dây Alpine Loop - Chính hãng VNA",
        desc: " Giảm trực tiếp 40%, tối đa 600.000 VNĐ khi mở thẻ TP Bank EVO",
        image: "bla...",
        categoryId: 3,
        price: 23990000,
        discount: 60,
        guarantee: 24,
      },
      {
        id: 24,
        name: "Apple Watch Ultra LTE 49mm Dây Trail Loop - Chính hãng VN/A",
        desc: "Giảm trực tiếp 40%, tối đa 600.000 VNĐ khi mở thẻ TP Bank EVO",
        image: "bla...",
        categoryId: 3,
        guarantee: 12,
        price: 23990000,
      },
      // end Apple>

      // Apple Macbook
      {
        id: 25,
        name: "MacBook Air 13 inch M1 LATE 2020 256GB - New seal Hàng Chính Hãng",
        desc: "Hỗ trợ trả góp 0% chỉ cần CCCD gắn chip hoặc 0% qua thẻ tín dụng",
        image: "bla...",
        categoryId: 4,
        price: 28990000,
        discount: 10,
        guarantee: 12,
      },
      {
        id: 26,
        name: "MacBook Air M2 13 inch 2022 8CPU 8GPU 256GB| RAM 8GB Chính hãng",
        image: "bla...",
        desc: "Cài đặt ứng dụng MIỄN PHÍ và phần mềm TRỌN ĐỜI MÁY.",
        categoryId: 4,
        price: 19990000,
        discount: 5,
        guarantee: 24,
      },
      {
        id: 27,
        name: "MacBook Air 13 inch M1 LATE 2020 512GB - New seal Hàng Chính Hãng",
        desc: "Hỗ trợ trả góp 0% chỉ cần CCCD gắn chip hoặc 0% qua thẻ tín dụng",
        image: "bla...",
        categoryId: 4,
        price: 34990000,
        discount: 30,
        guarantee: 14,
      },
      {
        id: 28,
        name: "MacBook Air 13 inch M1 LATE 2020 256GB l RAM 16GB- New seal Hàng",
        image: "bla...",
        desc: "Hỗ trợ trả góp 0% chỉ cần CCCD gắn chip hoặc 0% qua thẻ tín dụng",
        categoryId: 4,
        price: 34590000,
        guarantee: 12,
      },
      {
        id: 29,
        name: "Macbook Air M2 13 inch 2022 8CPU 8GPU 256GB| RAM 16GB Chính hãn",
        image: "bla...",
        categoryId: 4,
        price: 36990000,
        desc: "Hỗ trợ trả góp 0% chỉ cần CCCD gắn chip hoặc 0% qua thẻ tín dụng",
        discount: 12,
        guarantee: 12,
      },
      {
        id: 30,
        name: "MacBook Air M2 13inch 2022 8CPU 10GPU 512GB| RAM 8GB Chính hãng",
        desc: "Hỗ trợ trả góp 0% chỉ cần CCCD gắn chip hoặc 0% qua thẻ tín dụng",
        image: "bla...",
        categoryId: 4,
        price: 39390000,
        discount: 60,
        guarantee: 20,
      },
      {
        id: 31,
        name: "MacBook Air 13inch M1 LATE 2020 512GB l RAM 16GB - New seal Hàng",
        desc: "Hỗ trợ trả góp 0% chỉ cần CCCD gắn chip hoặc 0% qua thẻ tín dụng",
        image: "bla...",
        categoryId: 4,
        price: 45588000,
        discount: 20,
        guarantee: 24,
      },
      {
        id: 32,
        name: "MacBook Air 13 inch M1 LATE 2020 7GPU 512GB l RAM 16GB- New sea",
        desc: "Trả góp qua Home PayLater giảm thêm 5% tối đa 500.000đ.",
        image: "bla...",
        categoryId: 4,
        guarantee: 12,
        price: 37990000,
      },
      // end Macbook>
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     *
     */
    await queryInterface.bulkDelete("Products", null, {});
  },
};
